version: '2.1'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000"
    entrypoint: ["./wait-for-it.sh", "${DJANGO_DB_HOST}:${DJANGO_DB_PORT}", "--strict", "--timeout=300", "--"]
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn docker_django.wsgi:application -w 2 -b :8000"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "${HOST_NGINX_PORT}:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redisdata:/data

  database:
    build: ./${DB_TYPE}
    image: ${DB_TYPE}_db
    environment:
      # POSTGRES SPECIFIC
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      # MYSQL SPECIFIC
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${HOST_DATABASE_PORT:-$DB_PORT}:${DB_PORT}"
    volumes:
      - mysql-vol:/var/lib/mysql
      - pgdata:/var/lib/postgresql/data/
    container_name: ${DB_TYPE}_db

volumes:
  mysql-vol:
  redisdata:
  web-static:
